# 第一阶段：构建阶段
# 使用Go官方镜像作为构建环境
FROM golang:1.20 as go_builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy,direct
RUN go mod download
COPY . .
# 交叉编译
# 当 CGO_ENABLED=0 进行编译时，则会把在目标文件中未定义的符号（如外部函数）一起链接到可执行文件中。
RUN CGO_ENABLED=0 GOOS=linux go build -o main .
FROM alpine:latest
WORKDIR /app
COPY --from=go_builder /app/main .
COPY --from=go_builder /app/.env .
EXPOSE 3000
# 定义启动命令
CMD ["/app/main"]